### user 1
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "username": "sigma",
  "email": "sigma.syd@gmail.com",
  "password": "password"
}

### user 1
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "username": "fbarcos",
  "email": "fbarcos8@hotmail.com",
  "password": "password",
  "roles": [
    "admin",
    "moderator"
  ]
}

### user 3
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "username": "cbarcos",
  "email": "carlosbarcos@outlook.com",
  "password": "password",
  "roles": [
    "admin"
  ]
}

### user 4
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "username": "ciro",
  "email": "ciro@outlook.com",
  "password": "password",
  "roles": [
    "admin"
  ]
}