### user not found
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "fbarcos81@hotmail.com"
}

### user found but password invalid
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "fbarcos8@hotmail.com",
  "password": "123456"
}

### user found but password is missing
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "fbarcos8@hotmail.com"
}

### user found and password is ok with 2 roles
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "fbarcos8@hotmail.com",
  "password": "password"
}

### user found and password is ok without role
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "sigma.syd@gmail.com",
  "password": "password"
}

### create user with token without role
POST http://localhost:4000/api/users/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWIxZDk1NjM0Y2RhOTRjMmVlMTdmZSIsImlhdCI6MTY3OTk1MjkyMiwiZXhwIjoxNjgwMDM5MzIyfQ.I8KPPVF9qxHTMLcW71G-gQUq9RTq9KeogfEyTI-qy3M

{
  "email": "fbarcos8@hotmail.com",
  "password": "password"
}

### create user with token with admin role but role param does'nt exists
POST http://localhost:4000/api/users/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWIxYmQzYzBkZjZmYTBlZTcwOWJlYiIsImlhdCI6MTY3OTkyMTIzOCwiZXhwIjoxNjgwMDA3NjM4fQ.aZ7mfoxLlEzeSq49Az1aWr-7H3wbjfCcsxrjp42J87g

{
  "username":"cbarcos",
  "email": "carlosbarcos@outlook.com",
  "password": "password",
  "roles": ["superadmin","writer"]
}

### create user with token with admin role but role param right
POST http://localhost:4000/api/users/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWIxYmQzYzBkZjZmYTBlZTcwOWJlYiIsImlhdCI6MTY3OTkyMTIzOCwiZXhwIjoxNjgwMDA3NjM4fQ.aZ7mfoxLlEzeSq49Az1aWr-7H3wbjfCcsxrjp42J87g

{
  "username":"cbarcos",
  "email": "carlosbarcos@outlook.com",
  "password": "password",
  "roles": ["admin"]
}